baseurl: /enum-flags

github: # only for testing
  project_title: enum-flags
  project_tagline: Bit flags for C++11 scoped enums
  owner_name: grisumbras
  owner_url: https://github.com/grisumbras
  repository_url: https://github.com//grisumbras/enum-flags
  zip_url: https://github.com/grisumbras/enum-flags/zipball/master
  tar_url: https://github.com/grisumbras/enum-flags/tarball/master
  url: http://http://grisumbras.github.io/enum-flags/

markdown: kramdown

kramdown:
  input: GFM

permalink: pretty

exclude:
  - include
  - test
  - examples
  - README.md
  - LICENSE

sass:
  style: :compressed
